cfg = cfg or {} cfg.riderData = cfg.riderData or {}

cfg.riderData.rarity = {
    [1] = { label = "Local",     color = "#9ca3af", weight = 5500, tip_chance = 0.05, tip_amount = { min = 1,  max = 5 } },
    [2] = { label = "Regular",   color = "#22c55e", weight = 3000, tip_chance = 0.1,  tip_amount = { min = 5,  max = 10 } },
    [3] = { label = "Notable",   color = "#3b82f6", weight = 1250, tip_chance = 0.25, tip_amount = { min = 10, max = 20 } },
    [4] = { label = "VIP",       color = "#8b5cf6", weight = 200,  tip_chance = 0.5,  tip_amount = { min = 20, max = 40 } },
    [5] = { label = "Legend",    color = "#f97316", weight = 50,   tip_chance = 0.8,  tip_amount = { min = 40, max = 70 } },
    [6] = { label = "Celebrity", color = "#eab308", weight = 10,   tip_chance = 1.0,  tip_amount = { min = 70, max = 100 } },
}


cfg.riderData.npc = {
    { model = "a_m_m_skater_01", name = "Tony Marks", rarity = 1 },
    { model = "a_m_m_eastsa_01", name = "Rico Hernandez", rarity = 1 },
    { model = "a_m_m_beach_01", name = "Cody Blake", rarity = 1 },
    { model = "a_m_m_fatlatin_01", name = "Luis Ortega", rarity = 1 },
    { model = "a_m_m_hillbilly_01", name = "Cletus Brown", rarity = 1 },
    { model = "a_m_m_indian_01", name = "Raj Patel", rarity = 1 },
    { model = "a_m_m_mexlabor_01", name = "Pedro Garcia", rarity = 1 },
    { model = "a_m_m_og_boss_01", name = "Darnell White", rarity = 1 },
    { model = "a_m_m_prolhost_01", name = "Niko Jankovic", rarity = 1 },
    { model = "a_m_m_salton_01", name = "Earl Johnson", rarity = 1 },
    { model = "a_m_m_soucent_01", name = "Tyrone Smith", rarity = 1 },
    { model = "a_m_m_tramp_01", name = "Rusty Simmons", rarity = 1 },
    { model = "a_m_y_beach_01", name = "Kyle Brody", rarity = 1 },
    { model = "a_m_y_eastsa_01", name = "Javier Cruz", rarity = 1 },
    { model = "a_m_y_motox_01", name = "Chad Rogers", rarity = 1 },
    { model = "a_m_y_roadcyc_01", name = "Dustin Miller", rarity = 1 },
    { model = "a_m_y_skater_01", name = "Zach Wallace", rarity = 1 },
    { model = "a_m_y_soucent_01", name = "DeShawn Brown", rarity = 1 },
    { model = "a_m_y_stbla_01", name = "Frankie Lopez", rarity = 1 },
    { model = "a_m_y_vinewood_01", name = "Bradley Cooper", rarity = 1 },
    { model = "a_f_m_beach_01", name = "Sandy Moore", rarity = 1 },
    { model = "a_f_m_bevhills_01", name = "Patricia West", rarity = 1 },
    { model = "a_f_m_fatwhite_01", name = "Mary Beth Adams", rarity = 1 },
    { model = "a_f_m_ktown_01", name = "Soo-Jin Lee", rarity = 1 },
    { model = "a_f_m_soucentmc_01", name = "Latasha Brown", rarity = 1 },
    { model = "a_f_m_tourist_01", name = "Nancy Miller", rarity = 1 },
    { model = "a_f_o_genstreet_01", name = "Gloria King", rarity = 1 },
    { model = "a_f_o_ktown_01", name = "Mina Park", rarity = 1 },
    { model = "a_f_o_soucent_01", name = "Tameka Jones", rarity = 1 },
    { model = "a_f_y_beach_01", name = "Ashley Brooks", rarity = 1 },
    { model = "a_f_y_bevhills_01", name = "Monica Ruiz", rarity = 1 },
    { model = "a_f_y_bevhills_02", name = "Jenna Scott", rarity = 1 },
    { model = "a_f_y_clubcust_01", name = "Serena Lewis", rarity = 1 },

    { model = "a_m_m_business_01", name = "Victor Russo", rarity = 2 },
    { model = "a_m_m_paparazzi_01", name = "Harvey Stein", rarity = 2 },
    { model = "a_m_m_farmer_01", name = "Billy-Ray Boone", rarity = 2 },
    { model = "a_m_m_golfer_01", name = "Dennis Chambers", rarity = 2 },
    { model = "a_m_m_hasjew_01", name = "Morris Kleinman", rarity = 2 },
    { model = "a_m_m_soucent_02", name = "Marcus Jones", rarity = 2 },
    { model = "a_m_m_soucent_03", name = "Clarence Hill", rarity = 2 },
    { model = "a_m_y_beachvesp_01", name = "Lance Bishop", rarity = 2 },
    { model = "a_m_y_business_01", name = "Derrick Porter", rarity = 2 },
    { model = "a_m_y_golfer_01", name = "Rick Marshall", rarity = 2 },
    { model = "a_m_y_jetski_01", name = "Brent Taylor", rarity = 2 },
    { model = "a_m_y_runner_01", name = "Reggie Walker", rarity = 2 },
    { model = "a_m_y_surfer_01", name = "Mick Johnson", rarity = 2 },
    { model = "a_m_y_vinewood_02", name = "Chase Donnelly", rarity = 2 },
    { model = "a_m_y_vinewood_03", name = "Cole Simmons", rarity = 2 },
    { model = "a_f_y_vinewood_01", name = "Alexa Bennett", rarity = 2 },
    { model = "a_f_y_vinewood_02", name = "Samantha Price", rarity = 2 },
    { model = "a_f_y_vinewood_03", name = "Brooke Morgan", rarity = 2 },
    { model = "a_f_y_vinewood_04", name = "Vanessa Walker", rarity = 2 },
    { model = "a_f_y_yoga_01", name = "Lily Thompson", rarity = 2 },
    { model = "a_m_m_afriamer_01", name = "Lamar Mitchell", rarity = 2 },
    { model = "a_m_m_hasjew_01", name = "Yitzhak Cohen", rarity = 2 },
    { model = "a_m_m_stlat_02", name = "Carlos Rivera", rarity = 2 },
    { model = "a_m_y_beachvesp_02", name = "Noah Turner", rarity = 2 },

    { model = "a_m_y_hipster_01", name = "Eliot Kramer", rarity = 3 },
    { model = "a_m_y_hipster_02", name = "Damien Kross", rarity = 3 },
    { model = "a_m_y_hipster_03", name = "Noel Barrett", rarity = 3 },
    { model = "a_m_y_downtown_01", name = "Vinny Malone", rarity = 3 },
    { model = "a_m_m_malibu_01", name = "Cliff Ramsey", rarity = 3 },
    { model = "a_m_m_rurmeth_01", name = "Wade Tinsley", rarity = 3 },
    { model = "a_m_m_tourist_01", name = "Trevor Lang", rarity = 3 },
    { model = "a_m_m_acult_01", name = "Ethan Moon", rarity = 3 },
    { model = "a_m_o_acult_01", name = "Gavin Stone", rarity = 3 },
    { model = "a_m_o_soucent_01", name = "Otis Franklin", rarity = 3 },
    { model = "a_m_o_genstreet_01", name = "Jermaine Carter", rarity = 3 },
    { model = "a_m_o_ktown_01", name = "Jun Park", rarity = 3 },
    { model = "a_m_y_busicas_01", name = "Malik Hughes", rarity = 3 },
    { model = "a_m_y_clubcust_02", name = "Leo Campbell", rarity = 3 },
    { model = "a_m_y_clubcust_03", name = "Julian Price", rarity = 3 },
    { model = "a_m_y_dhill_01", name = "Donovan Reed", rarity = 3 },
    { model = "a_m_y_hiker_01", name = "Logan Brooks", rarity = 3 },
    { model = "a_m_y_ktown_02", name = "Jae Kim", rarity = 3 },
    { model = "a_m_y_latino_01", name = "Luis Alvarez", rarity = 3 },
    { model = "a_m_y_musclbeac_02", name = "Chase Carter", rarity = 3 },
    { model = "a_m_y_stbla_02", name = "Andre Clark", rarity = 3 },
    { model = "a_m_y_stwhi_02", name = "Brandon Hall", rarity = 3 },
    { model = "a_m_y_sunbathe_01", name = "Trent Wallace", rarity = 3 },
    { model = "a_m_y_yoga_01", name = "Tanner Green", rarity = 3 },

    { model = "a_m_y_hasjew_01", name = "Mendel Horowitz", rarity = 4 },
    { model = "a_m_m_socenlat_01", name = "Rafael Mendez", rarity = 4 },
    { model = "a_m_m_stlat_02", name = "Dominic Alvarez", rarity = 4 },
    { model = "a_m_m_mlcrisis_01", name = "Victor DeLuca", rarity = 4 },
    { model = "a_m_y_busicas_01", name = "Orlando Price", rarity = 4 },
    { model = "a_m_y_genstreet_01", name = "Travis King", rarity = 4 },
    { model = "a_m_y_genstreet_02", name = "Andre Lewis", rarity = 4 },
    { model = "a_m_y_ktown_01", name = "Min-Soo Han", rarity = 4 },
    { model = "a_m_y_stwhi_01", name = "Curtis Beck", rarity = 4 },
    { model = "a_m_y_smartcaspat_01", name = "Preston Ward", rarity = 4 },   
    { model = "a_f_y_hipster_03", name = "Lena Cohen", rarity = 4 },
    { model = "a_f_y_hipster_04", name = "Maya Patel", rarity = 4 },
    { model = "a_f_y_soucent_01", name = "Keisha Wilson", rarity = 4 },
    { model = "a_f_y_soucent_02", name = "Desiree Allen", rarity = 4 },
    { model = "a_f_y_soucent_03", name = "Shawna Harris", rarity = 4 }, 

    { model = "a_m_y_hippy_01", name = "River Dawson", rarity = 5 },
    { model = "a_m_y_roadcyc_01", name = "Scott Hayward", rarity = 5 },
    { model = "a_m_y_bevhills_01", name = "Lorenzo Russo", rarity = 5 },
    { model = "a_m_y_bevhills_02", name = "Mitchell Grant", rarity = 5 },
    { model = "a_m_y_musclbeac_01", name = "Randy Cobb", rarity = 5 },
    { model = "a_m_y_musclbeac_02", name = "Dallas Cortez", rarity = 5 },
    { model = "csb_abigail", name = "Abigail Mathers", rarity = 5 },
    { model = "a_f_y_eastsa_01", name = "Rosa Ramirez", rarity = 5 },
    { model = "a_f_y_eastsa_02", name = "Yolanda Morales", rarity = 5 },
    { model = "a_f_y_genhot_01", name = "Veronica Carter", rarity = 5 },
    { model = "a_f_y_hipster_01", name = "Sierra Bell", rarity = 5 },
    { model = "a_f_y_hipster_02", name = "Harper Davis", rarity = 5 },
    
    { model = "csb_stripper_01", name = "Cinnamon", rarity = 6 },
    { model = "u_m_y_pogo_01", name = "Pogo the Fool", rarity = 6 },
    { model = "s_m_m_strperf_01", name = "Silas Stone", rarity = 6 },    
    { model = "player_zero", name = "Michael De Santa", rarity = 6 },
    { model = "player_one",  name = "Franklin Clinton", rarity = 6 },
    { model = "player_two",  name = "Trevor Philips", rarity = 6 },

}


cfg.riderData.idleScenes ={
    "WORLD_HUMAN_STAND_IMPATIENT",
    "WORLD_HUMAN_STAND_IMPATIENT_UPRIGHT",
    "WORLD_HUMAN_STAND_MOBILE",
    "WORLD_HUMAN_STAND_MOBILE_UPRIGHT",
    "WORLD_HUMAN_LEANING",
    "CODE_HUMAN_CROSS_ROAD_WAIT",
    "WORLD_HUMAN_SMOKING",
    "WORLD_HUMAN_SMOKING_POT",
    "WORLD_HUMAN_DRINKING",
    "WORLD_HUMAN_AA_COFFEE",
    "WORLD_HUMAN_BINOCULARS",
    "WORLD_HUMAN_MOBILE_FILM_SHOCKING",
    "WORLD_HUMAN_JOG_STANDING",
    "WORLD_HUMAN_HIKER_STANDING",
}
